services:
    _defaults:
        autowire: true
        autoconfigure: true


    numero2_maileon.api.maileon:
        class: numero2\MaileonBundle\API\MaileonApi
        public: true
        arguments:
            - '@http_client'
            - '@monolog.logger.contao.error'


    numero2_maileon.cron.send_integration_event:
        class: numero2\MaileonBundle\Cron\SendIntegrationEventCron
        arguments:
            - '@database_connection'
            - '@numero2_maileon.api.maileon'